from .css import FormatMinifyCSSView
from .html import FormatMinifyHTMLView
from .json import FormatMinifyJSONView
from .markdown import FormatMinifyMakrDownView
from .sql import FormatMinifySQLView
from .xml import FormatMinifyXMLView
from .js import FormatMinifyJSView
from .yml import FormatMinifyYMLView
from .csharp import FormatMinifyCSharpView